In [146]:
# Keith Galli numpy video 
import numpy as np 
import sys 

a = np.array([
    [ [1] ],
    
    [ [2] ],
    
    [ [3,2] ]
            ]) # can specify dtype='xxx'
a
a.ndim # dimension of list 
a.shape # if not three elements in tuple, means the list are of different size from there on wards 
a.dtype # get datatype
a.itemsize
a.size
a.nbytes

b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b
b[1,5] # can also use negative notation like in list 
b[1,]
b[:,1] # get 2nd column 
#[start:stepsize,end:stepsize]
b
b[0,1:len(b[0]):2]
b[0,0] = 99
b

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c.shape
c
# Get specific element (work outside in)
c[0,1,1]
# c[:,1,:] = [[9,9,9],[8,8]] # get an error 

# All 0s matrix
np.zeros((2,3))

# All 1s matrix
np.ones((4,2,2), dtype='int32')

# Any other number
np.full((2,2), 99)

# Any other number (full_like)
np.full_like(a, 4) # same structure/shape like a with values of 4 

# Random decimal numbers
np.random.rand(4,2) # specify the shape 

# Random Integer values
np.random.randint(-4,8, size=(3,3))

# The identity matrix
np.identity(5)

# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0) # axis 0 is row 
r1

output = np.ones((5,5))
output

z = np.zeros((3,3))
z[1,1] = 9
z

output[1:-1,1:-1] = z
output

# Be careful when copying arrays 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
# print(a)

a = np.array([1,2,3,4])
# print(a+2)
b = np.array([1,0,1,0])
# print(a + b)
# print(a ** 2)
# print(np.cos(a))
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algera 
a = np.ones((2,3))
# print(a)
b = np.full((3,2), 2)
# print(b)
np.matmul(a,b) # matrix multiplication 

# Find the determinant
c = np.identity(3)
np.linalg.det(c)

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Statistics 
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)
# print(np.max(stats, axis=1)) # 3 for row 1 and 6 for row 2 
# print(np.sum(stats, axis=0)) # column 

# Reorganizing arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
# print(before)

# after = before.reshape((2,3)) # error because must be same size 

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
# print(np.vstack([v1,v2]))

# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
# print(np.hstack((h1,h2)))

# Load data from file 
filedata = np.genfromtxt('data.txt', delimiter=',')
# print(filedata)
# print()
filedata = filedata.astype('int32')
# print(filedata)

# Boolean Masking and Advanced Indexing
(~((filedata > 50) & (filedata < 100))) # we want to know which data is between 50 and 100, not inclusive

# Can index in numpy with list 
bb = np.array([1,2,3,4,5,6,7,8,9])
bb[[0,1,2]]

# One quick challenge 
question = np.array([1,2,3,4,5],dtype='int32')
question
i = 6
temp = np.array([],dtype='int32')
while i < 31:
    if i % 5 == 0:
        temp = np.append(temp,i)
        question = np.vstack([question,temp])
        temp = np.array([],dtype='int32')
    else:
        temp = np.append(temp,i)
    i += 1
question

print(question[2:4,0:2])
print(question[[0,1,2,3],[1,2,3,4]])
print(question[[0,4,5],3:])


[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
